# Generated by Django 5.0.3 on 2024-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_complaint_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='downtime',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Время простоя в днях', null=True, verbose_name='Время простоя в днях'),
        ),
    ]
